# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  pathToSolution:  'PizzaBoxSolution'
  pathToProject:  'PizzaBoxSolution/PizzaBox'
  pathToTest:  'PizzaBoxSolution/RestaurantTest'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'PizzaBoxSonar'
    organization: 'fredbrume-github'
    scannerMode: 'MSBuild'
    projectKey: 'f06b519749ddb9fa491e06d3f26b6f4e006c429f'
  displayName: 'Sonar Prepare Analysis'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: '$(pathToSolution)'

- task: DotNetCoreCLI@1
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: 'configuration Release'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'









