# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pathToSolution:  'PizzaBoxSolution/'
  pathToProject:  'PizzaBoxSolution/PizzaBox/'
  pathToTest:  'PizzaBoxSolution/PizzaboxTest/Test/'


# SONAR PREPARE ANALYSIS CONFIG
steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'PizzaBoxSonar'
    organization: 'fredbrume-github'
    scannerMode: 'MSBuild'
    projectKey: 'f06b519749ddb9fa491e06d3f26b6f4e006c429f'
    projectName: 'SonarCloud Analysis'
  displayName: 'Sonar Prepare Analysis'

#BUILD
- task: DotNetCoreCLI@1
  displayName: Build
  inputs:
    command: build
    projects: '$(pathToProject)'
    arguments: '$(buildConfiguration)'

#BASIC TEST
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '$(pathToTest)'
    arguments: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '*.trx'
    searchFolder: '$(Build.ArtifactStagingDirectory)/test'
  displayName: 'Publish Test Results'





    










